FROM node:22-slim AS base
WORKDIR /app

FROM base AS deps
COPY package.json package-lock.json ./
COPY workers/monitor/package.json workers/monitor/package.json
COPY packages packages
RUN npm ci

FROM deps AS runner
COPY . .
CMD ["npm", "run", "start", "--workspace", "@pokemon-monitor/monitor-worker"]
